import { supabaseAdmin } from "./supabase.service.js";

class PrintSessionService {
  // ============================================================
  // SHOP / QR
  // ============================================================

  /**
   * Resolve a permanent public QR code to a shop.
   *
   * public_code is intentionally the only public shop identifier
   * exposed through the QR flow.
   */
  async getShopByPublicCode(publicCode) {
    return await supabaseAdmin
      .from("shops")
      .select(`
        id,
        shop_name,
        block,
        organisation_id,
        owner_id,
        is_active,
        is_accepting_orders,
        public_code
      `)
      .eq("public_code", publicCode)
      .single();
  }

  // ============================================================
  // SESSION CREATION
  // ============================================================

  /**
   * Create a new anonymous print session for a shop.
   *
   * The session token is generated by PostgreSQL because the
   * print_sessions.session_token column has a gen_random_uuid()
   * default.
   */
  async createSession({
    shopId,
    organisationId,
  }) {
    return await supabaseAdmin
      .from("print_sessions")
      .insert({
        shop_id: shopId,
        organisation_id: organisationId,
        status: "created",
        last_customer_seen: new Date().toISOString(),
      })
      .select(`
        id,
        shop_id,
        organisation_id,
        session_token,
        customer_name,
        customer_phone,
        status,
        quoted_amount,
        quoted_at,
        quoted_by,
        last_customer_seen,
        last_vendor_seen,
        expires_at,
        created_at,
        updated_at
      `)
      .single();
  }

  // ============================================================
  // CUSTOMER SESSION ACCESS
  // ============================================================

  /**
   * Retrieve a session using the temporary customer token.
   *
   * This is the primary authorization mechanism for anonymous
   * customer requests.
   */
  async getSessionByToken(sessionToken) {
    return await supabaseAdmin
      .from("print_sessions")
      .select(`
        id,
        shop_id,
        organisation_id,
        session_token,
        customer_name,
        customer_phone,
        status,
        quoted_amount,
        quoted_at,
        quoted_by,
        last_customer_seen,
        last_vendor_seen,
        expires_at,
        created_at,
        updated_at,
        shops (
          id,
          shop_name,
          block,
          is_active,
          is_accepting_orders
        )
      `)
      .eq("session_token", sessionToken)
      .single();
  }

  /**
   * Save customer information against the session.
   */
  async submitCustomerDetails(
    sessionId,
    {
      customerName,
      customerPhone,
    }
  ) {
    return await supabaseAdmin
      .from("print_sessions")
      .update({
        customer_name: customerName,
        customer_phone: customerPhone,
        status: "customer_details",
        last_customer_seen: new Date().toISOString(),
      })
      .eq("id", sessionId)
      .select(`
        id,
        shop_id,
        organisation_id,
        session_token,
        customer_name,
        customer_phone,
        status,
        quoted_amount,
        quoted_at,
        expires_at,
        created_at,
        updated_at
      `)
      .single();
  }

  // ============================================================
  // CUSTOMER HEARTBEAT
  // ============================================================

  async updateCustomerHeartbeat(sessionId) {
    return await supabaseAdmin
      .from("print_sessions")
      .update({
        last_customer_seen: new Date().toISOString(),
      })
      .eq("id", sessionId)
      .select("id, last_customer_seen")
      .single();
  }

  // ============================================================
  // VENDOR HEARTBEAT
  // ============================================================

  async updateVendorHeartbeat(sessionId) {
    return await supabaseAdmin
      .from("print_sessions")
      .update({
        last_vendor_seen: new Date().toISOString(),
      })
      .eq("id", sessionId)
      .select("id, last_vendor_seen")
      .single();
  }

  // ============================================================
  // VENDOR SESSION ACCESS
  // ============================================================

  /**
   * Verify that a session belongs to a shop owned by the
   * authenticated vendor.
   *
   * This is intentionally done server-side because session
   * operations use the service-role client.
   */
  async getSessionForOwner(sessionId, ownerId) {
    return await supabaseAdmin
      .from("print_sessions")
      .select(`
        id,
        shop_id,
        organisation_id,
        session_token,
        customer_name,
        customer_phone,
        status,
        quoted_amount,
        quoted_at,
        quoted_by,
        last_customer_seen,
        last_vendor_seen,
        expires_at,
        created_at,
        updated_at,
        shops!inner (
          id,
          shop_name,
          block,
          owner_id,
          organisation_id
        )
      `)
      .eq("id", sessionId)
      .eq("shops.owner_id", ownerId)
      .single();
  }

  // ============================================================
  // LIVE SESSIONS
  // ============================================================

  /**
   * Get active sessions belonging to the authenticated vendor's
   * shop.
   */
  async getLiveSessionsForOwner(ownerId) {
    return await supabaseAdmin
      .from("print_sessions")
      .select(`
        id,
        shop_id,
        organisation_id,
        session_token,
        customer_name,
        customer_phone,
        status,
        quoted_amount,
        quoted_at,
        last_customer_seen,
        last_vendor_seen,
        expires_at,
        created_at,
        updated_at,
        session_documents (
          id,
          original_filename,
          mime_type,
          file_size,
          upload_status,
          uploaded_at,
          page_count,
          created_at
        ),
        shops!inner (
          id,
          shop_name,
          block,
          owner_id
        )
      `)
      .eq("shops.owner_id", ownerId)
      .not(
        "status",
        "in",
        '("completed","archived","expired")'
      )
      .order("created_at", {
        ascending: false,
      });
  }

  // ============================================================
  // SESSION DOCUMENTS
  // ============================================================

  /**
   * Get all documents belonging to a session.
   *
   * The controller/service must validate the session token or
   * vendor ownership before calling this method.
   */
  async getSessionDocuments(sessionId) {
    return await supabaseAdmin
      .from("session_documents")
      .select(`
        id,
        session_id,
        original_filename,
        storage_key,
        mime_type,
        file_size,
        upload_status,
        uploaded_at,
        page_count,
        created_at,
        updated_at
      `)
      .eq("session_id", sessionId)
      .order("created_at", {
        ascending: true,
      });
  }

  /**
   * Create metadata for a document before direct B2 upload.
   */
  async createSessionDocument({
    sessionId,
    originalFilename,
    storageKey,
    mimeType,
    fileSize,
  }) {
    return await supabaseAdmin
      .from("session_documents")
      .insert({
        session_id: sessionId,
        original_filename: originalFilename,
        storage_key: storageKey,
        mime_type: mimeType,
        file_size: fileSize,
        upload_status: "uploading",
      })
      .select(`
        id,
        session_id,
        original_filename,
        storage_key,
        mime_type,
        file_size,
        upload_status,
        uploaded_at,
        page_count,
        created_at,
        updated_at
      `)
      .single();
  }

  /**
   * Mark an individual document as successfully uploaded.
   */
  async markDocumentUploaded(
    documentId,
    {
      pageCount = null,
    } = {}
  ) {
    return await supabaseAdmin
      .from("session_documents")
      .update({
        upload_status: "uploaded",
        uploaded_at: new Date().toISOString(),
        page_count: pageCount,
      })
      .eq("id", documentId)
      .select(`
        id,
        session_id,
        original_filename,
        storage_key,
        mime_type,
        file_size,
        upload_status,
        uploaded_at,
        page_count,
        created_at,
        updated_at
      `)
      .single();
  }

  /**
   * Mark an individual document as failed.
   */
  async markDocumentFailed(documentId) {
    return await supabaseAdmin
      .from("session_documents")
      .update({
        upload_status: "failed",
      })
      .eq("id", documentId)
      .select(`
        id,
        session_id,
        original_filename,
        storage_key,
        mime_type,
        file_size,
        upload_status,
        uploaded_at,
        page_count,
        created_at,
        updated_at
      `)
      .single();
  }

  // ============================================================
  // SESSION QUOTE
  // ============================================================

  /**
   * Vendor enters the final amount discussed face-to-face.
   *
   * No pricing engine is involved.
   */
  async setQuote(sessionId, ownerId, amount) {
  const { data: session, error: sessionError } =
    await this.getSessionForOwner(sessionId, ownerId);

  if (sessionError || !session) {
    return {
      data: null,
      error: {
        message: "Session not found or access denied",
      },
    };
  }

  return await supabaseAdmin
    .from("print_sessions")
    .update({
      quoted_amount: amount,
      quoted_at: new Date().toISOString(),
      quoted_by: ownerId,
      status: "quote_ready",
      last_vendor_seen: new Date().toISOString(),
    })
    .eq("id", sessionId)
    .select(`
      id,
      shop_id,
      organisation_id,
      session_token,
      customer_name,
      customer_phone,
      status,
      quoted_amount,
      quoted_at,
      quoted_by,
      last_customer_seen,
      last_vendor_seen,
      expires_at,
      created_at,
      updated_at
    `)
    .single();
}

  // ============================================================
  // SESSION STATUS
  // ============================================================
async updateSessionStatus(sessionId, ownerId, status) {
  const { data: session, error: sessionError } =
    await this.getSessionForOwner(sessionId, ownerId);

  if (sessionError || !session) {
    return {
      data: null,
      error: {
        message: "Session not found or access denied",
        status: 403,
      },
    };
  }

  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status,
      last_vendor_seen: new Date().toISOString(),
    })
    .eq("id", sessionId)
    .select(`
      id,
      shop_id,
      organisation_id,
      session_token,
      customer_name,
      customer_phone,
      status,
      quoted_amount,
      quoted_at,
      quoted_by,
      last_customer_seen,
      last_vendor_seen,
      expires_at,
      created_at,
      updated_at
    `)
    .single();
}

async connectSession(sessionId) {
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "connected",
      last_customer_seen: new Date().toISOString(),
    })
    .eq("id", sessionId)
    .eq("status", "created")
    .select()
    .single();
}

async getSessionByToken(sessionToken) {
  return await supabaseAdmin
    .from("print_sessions")
    .select("*")
    .eq("session_token", sessionToken)
    .single();
}


async startFileUpload(sessionToken) {
  // 1. Find session
  const {
    data: session,
    error: sessionError,
  } = await supabaseAdmin
    .from("print_sessions")
    .select("*")
    .eq("session_token", sessionToken)
    .single();

  if (sessionError || !session) {
    return {
      error: {
        message: "Print session not found",
      },
    };
  }

  // 2. Validate current state
  if (session.status !== "customer_details") {
    return {
      error: {
        message:
          `Cannot start file upload from status ${session.status}`,
      },
    };
  }

  // 3. Transition
  const {
    data,
    error,
  } = await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "files_uploading",
    })
    .eq("id", session.id)
    .eq("status", "customer_details")
    .select()
    .single();

  if (error) {
    return {
      error,
    };
  }

  return {
    data,
  };
}



async addSessionFile(fileData) {
  return await supabaseAdmin
    .from("print_session_files")
    .insert(fileData)
    .select()
    .single();
}

async getSessionFiles(sessionId) {
  return await supabaseAdmin
    .from("print_session_files")
    .select(`
      id,
      session_id,
      file_key,
      file_name,
      mime_type,
      file_size,
      page_count,
      created_at
    `)
    .eq("session_id", sessionId)
    .order("created_at", {
      ascending: true,
    });
}

async getSessionFile(fileId) {
  return await supabaseAdmin
    .from("print_session_files")
    .select(`
      id,
      session_id,
      file_key,
      file_name,
      mime_type,
      file_size,
      page_count,
      created_at
    `)
    .eq("id", fileId)
    .single();
}


async markFilesUploaded(sessionId) {
  // First make sure at least one file exists
  const {
    count,
    error: countError,
  } = await supabaseAdmin
    .from("print_session_files")
    .select("id", {
      count: "exact",
      head: true,
    })
    .eq("session_id", sessionId);

  if (countError) {
    return {
      error: countError,
    };
  }

  if (!count || count < 1) {
    return {
      error: {
        message:
          "Cannot mark files uploaded without files",
      },
    };
  }

  // Move session forward
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "files_uploaded",
    })
    .eq("id", sessionId)
    .eq("status", "files_uploading")
    .select()
    .single();
}


async getSessionForShop(sessionToken, shopId) {
  return await supabaseAdmin
    .from("print_sessions")
    .select(`
      id,
      shop_id,
      organisation_id,
      session_token,
      customer_name,
      customer_phone,
      status,
      quoted_amount,
      quoted_at,
      expires_at,
      created_at,
      updated_at,

      print_session_files (
        id,
        file_name,
        file_key,
        file_size,
        mime_type,
        created_at
      )
    `)
    .eq("session_token", sessionToken)
    .eq("shop_id", shopId)
    .single();
}

async getActiveSessionsForShop(shopId) {
  return await supabaseAdmin
    .from("print_sessions")
    .select(`
      id,
      shop_id,
      organisation_id,
      session_token,
      customer_name,
      customer_phone,
      status,
      quoted_amount,
      quoted_at,
      expires_at,
      created_at,
      updated_at
    `)
    .eq("shop_id", shopId)
    .in("status", [
      "connected",
      "customer_details",
      "files_uploading",
      "files_uploaded",
      "reviewing",
      "quote_ready",
      "payment_pending"
    ])
    .order("created_at", {
      ascending: false,
    });
}


async createSessionQuote(sessionToken, shopId, quotedAmount) {
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      quoted_amount: quotedAmount,
      quoted_at: new Date().toISOString(),
      status: "quote_ready",
    })
    .eq("session_token", sessionToken)
    .eq("shop_id", shopId)
    .select()
    .single();
}


async markSessionReviewing(sessionToken, shopId) {
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "reviewing",
    })
    .eq("session_token", sessionToken)
    .eq("shop_id", shopId)
    .select()
    .single();
}

async getSessionForPayment(sessionToken) {
  return await supabaseAdmin
    .from("print_sessions")
    .select(`
      id,
      shop_id,
      organisation_id,
      session_token,
      status,
      quoted_amount,
      quoted_at,
      expires_at
    `)
    .eq("session_token", sessionToken)
    .single();
}

async createSessionPayment(data) {
  return await supabaseAdmin
    .from("session_payments")
    .insert(data)
    .select()
    .single();
}

async getSessionPaymentBySession(sessionId) {
  return await supabaseAdmin
    .from("session_payments")
    .select("*")
    .eq("session_id", sessionId)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();
}

async markSessionPaymentSuccess(
  razorpayOrderId,
  razorpayPaymentId,
  razorpaySignature
) {
  return await supabaseAdmin
    .from("session_payments")
    .update({
      status: "success",
      razorpay_payment_id: razorpayPaymentId,
      razorpay_signature: razorpaySignature,
      updated_at: new Date().toISOString(),
    })
    .eq("razorpay_order_id", razorpayOrderId);
}

async getSessionPaymentByRazorpayOrder(razorpayOrderId) {
  return await supabaseAdmin
    .from("session_payments")
    .select("*")
    .eq("razorpay_order_id", razorpayOrderId)
    .single();
}

async markSessionPaymentPending(sessionToken) {
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "payment_pending",
      updated_at: new Date().toISOString(),
    })
    .eq("session_token", sessionToken)
    .eq("status", "quote_ready")
    .select()
    .single();
}

async markSessionPaid(sessionToken) {
  return await supabaseAdmin
    .from("print_sessions")
    .update({
      status: "paid",
      updated_at: new Date().toISOString(),
    })
    .eq("session_token", sessionToken)
    .eq("status", "payment_pending")
    .select()
    .single();
}




}

export default new PrintSessionService();